project_id = "uwfadiatyiuavtgzbcar"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://uwfadiatyiuavtgzbcar.supabase.co"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
enabled = true
port = 54322
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 1025
pop3_port = 1110

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
file_transform_limit = "1GiB"

[edge_runtime]
enabled = true
port = 54326
ip_version = "ipv4"

[analytics]
enabled = false
port = 54327
vector_port = 54328
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcp.json"

[functions.calculate-professional-wind]
verify_jwt = false

[functions.get-pressure-coefficients]
verify_jwt = false