// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwfadiatyiuavtgzbcar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3ZmFkaWF0eWl1YXZ0Z3piY2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDg4MTIsImV4cCI6MjA2NzU4NDgxMn0.6zeaXLZWvfYxCJZ0G6VYqrB1TXy-dpksl_F1S3yB6SA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});